# Generated by Django 3.2.3 on 2022-05-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220122_2028'),
        ('tienda', '0004_auto_20210222_1202'),
    ]

    operations = [
    ]
